

###
POST http://localhost:8080/subscribers/auth/register
Content-Type: application/json

{
    "username":"rose",
    "password":"12345678"
}


###
POST http://localhost:8080/subscribers/auth/login
Content-Type: application/json

{
    "username":"rose",
    "password":"12345678"
}



###
GET http://localhost:8080/subscribers/getAll

###
GET http://localhost:8080/subscribers/getUser/65aa226643ac4e8596486f97



###
POST http://localhost:8080/subscribers
Content-Type: application/json

{
    "name":"faseeh sub2",
    "subscribedToChannel":"tech simple web"
}


###

DELETE http://localhost:8080/subscribers/65aa223343ac4e8596486f93



###

PATCH http://localhost:8080/subscribers/65aa223343ac4e8596486f93

Content-Type: application/json

{
    "name":"New Name"
}
